### ISSUE TITLE
Accept Swedish NINs in format YYMMDDNNNN

### ISSUE THREAD

**Issue by themichaelhall** [vladdeSV/php-nin#7]
Personal views: As far as I know, this is the most common way to say a personal identification number. Also when log in to Swedbank, 10 digits without hyphen is accepted and that is what I usually type in. SEB seems to accept 10 digits only (login with DigiPass).

I think it's fair to assume that persons over 100 years are aware of the issue with 10 digits and probably uses the 12 digit version and therefore it's safe to assume that 10 digits numbers can be interpreted as an age below 100 years.

**Comment by vladdeSV** [comment]
I approve of this.
